#! /usr/bin/env bash
set -e

# go to DOTFILES folder
DOTFILES=$HOME/programming/aux/.dotfiles
cd $DOTFILES

# load stow folders
#STOW_FOLDERS=("bash" "i3" "nvim" "tmux" "bin" "alacritty" "picom")
STOW_FOLDERS=("nvim" "tmux" "bin")

# Installing all dotfiles
for folder in ${STOW_FOLDERS[@]}; do
    echo Installing $folder...
#    Use adopt with caution! It will replace target files. Use `stow -nvt ~` to see the changes first.
#    stow --adopt -vt ~ $folder
    stow -vt ~ $folder
done
echo Done!

sudo ln -fs /usr/bin/nvim /usr/bin/vi
sudo ln -fs /usr/bin/nvim /usr/bin/vim

# come back to the previous working dir
cd -
