#! /usr/bin/env bash
set -e

if [ ! -f "env/.dotfiles.env" ]; then
	cp env/.dotfiles.env.template env/.dotfiles.env
fi

source env/.dotfiles.env

# go to DOTFILES folder
cd $DOTFILES

# Installing all dotfiles
for folder in ${STOW_FOLDERS[@]}; do
	echo Installing $folder...
	#    Use adopt with caution! It will replace target files. Use `stow -nvt ~` to see the changes first.
	#    stow --adopt -vt ~ $folder
	stow -vt ~ $folder
done
echo Done!

# The java version is required by JDTLS
# TODO I need to to something like this to not apply the JAVA_HOME globally!
# nvim() {
#   export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
#   /usr/bin/nvim "$@"
# }
echo "export JAVA_HOME=/usr/lib/jvm/jdk-17 && nvim" | sudo tee /usr/bin/vi
sudo ln -fs /usr/bin/vi /usr/bin/vim
sudo chmod +x /usr/bin/vi
sudo chmod +x /usr/bin/vim

# come back to the previous working dir
cd -
