# This is how you pass env. variables to sway
# You can view these by executing:
# systemctl --user show-environment
# if you make changes to this file you can execute following command to reload manually:
# systemctl --user daemon-reload
JAVA_TOOL_OPTIONS=-Djdk.util.zip.disableZip64ExtraFieldValidation=true --add-opens=java.base/com.sun.crypto.provider=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
